### ISSUE TITLE
Wrong country in WWW 2020

### ISSUE THREAD

**Issue by YIWEI-CHEN** [JackieTseng/conference_call_for_paper#14]
### Taiwan is not a part of China (PROC). 

The government of Taiwan is **Republic of China (ROC)** rather than People Republic of China (PROC). Please remove the flag of PROC in WWW 2020. 
Thank you.

**Comment by yike-chen** [comment]
Taiwan is now part of China(PROC).

**Comment by yfsong0709** [comment]
You know, for most countries and international organizations, PROC is a country while ROC is only a region.

**Comment by developfeng** [comment]
Taiwan is not only now, but allways a part of China (PROC).

**Comment by YIWEI-CHEN** [comment]
In my opinion, I can understand that China citizens believe TW is part of the PROC, while ROC is a region. I do not want you to admit ROC is another independent country. In fact, TW and Mainland are governed by different entities, that use different flag, currency, and form of government. Please remove the PROC flag in WWW 2020 to reflect this fact. You do not have to put the ROC flag in the row.

**Comment by asc5543** [comment]
Taiwan is NOT a part of China(PROC).
This is an issue.

**Comment by mhguo324** [comment]
Taiwan is not a part of China. 
Mr. Tseng modified the flag from ROC to PROC 11 days ago. Please remove the PROC flag.

**Comment by miajhaochen** [comment]
> In my opinion, I can understand that China citizens believe TW is part of the PROC, while ROC is a region. I do not want you to admit ROC is another independent country. In fact, TW and Mainland are governed by different entities, that use different flag, currency, and form of government. Please remove the PROC flag in WWW 2020 to reflect this fact. You do not have to put the ROC flag in the row.

Cannot agree more. Taiwan is not part of China.

**Comment by yike-chen** [comment]
Firstly, people on both sides of the Taiwan Straits belong to one big family. As long as we continue to adhere to the one-China principle and the 1992 Consensus, oppose Taiwan independence and uphold peaceful development of cross-Straits relations. Secondly, The international community, including the United Nations, recognizes that Taiwan belongs to China.

**Comment by corytu** [comment]
> Firstly, people on both sides of the Taiwan Straits belong to one big family. As long as we continue to adhere to the one-China principle and the 1992 Consensus, oppose Taiwan independence and uphold peaceful development of cross-Straits relations. Secondly, The international community, including the United Nations, recognizes that Taiwan belongs to China.

First of all, the PRC government has never had sovereignty over Taiwan, neither de facto nor de jure. In Treaty of San Francisco, Japan merely renounced its title and right over Taiwan and Penghu without transferring the power to specific entities.

To say the least, the 1992 Consensus - while actually no substantial consensus was formed in that meeting - is "_both sides recognize there is only one 'China': both mainland China and Taiwan belong to the same China, but both sides agree to interpret the meaning of that one China according to their own definition._" Putting the PRC flag next to Taiwan apparently dispute Taiwan's rights to define "China" and therefore violates the consensus. This is then nothing but bullying.

**Comment by yike-chen** [comment]
> > Firstly, people on both sides of the Taiwan Straits belong to one big family. As long as we continue to adhere to the one-China principle and the 1992 Consensus, oppose Taiwan independence and uphold peaceful development of cross-Straits relations. Secondly, The international community, including the United Nations, recognizes that Taiwan belongs to China.
> 
> First of all, the PRC government has never had sovereignty over Taiwan, neither de facto nor de jure. In Treaty of San Francisco, Japan merely renounced its title and right over Taiwan and Penghu without transferring the power to specific entities.
> 
> To say the least, the 1992 Consensus - while actually no substantial consensus was formed in that meeting - is "_both sides recognize there is only one 'China': both mainland China and Taiwan belong to the same China, but both sides agree to interpret the meaning of that one China according to their own definition._" Putting the PRC flag next to Taiwan apparently despises Taiwan's rights to define "China" and therefore violates the consensus. This is then nothing but bullying.

First of all, the People's Republic of China(PRC) government has not recognized the San Francisco Peace Treaty since it signed. It is completely unreasonable for Taiwan independence to take something that the People's Republic of China(PRC) does not recognize at all. 

Secondly, the 1992 Consensus only recognizes the People's Republic of China(PRC). The People's Republic of China has never acknowledged the two definitions that you have said. It is entirely the fabrication of Taiwan independence. 

In the end, Taiwan has never been recognized internationally as an independent country and region, but is part of the People's Republic of China. Fabricating Taiwan as an independent region is entirely a Taiwan independence act of self-indulgence. 

Why do you dare not reply to Taiwan authorities have not been recognized by the international community. What you said is not recognized by the People's Republic of China.

**Comment by wenhanjin** [comment]
Taiwan is a part of China.
Please those who support Taiwan independence reflect on their own seriously  where they come form in history.

**Comment by wenhanjin** [comment]
Taiwan is a part of China.
Please those who support Taiwan independence reflect on their own seriously where they come from in history.

**Comment by Yannnnnnnnnnnn** [comment]
@corytu 
臺灣的先民要是知道後代成了這個樣子，不知做會做何感想。
如果留下一點爭辯的時間，稍微去學習一點臺灣歷史就能大概瞭解臺灣究竟和大陸之間的關係。只不過因爲日據時代，連國民黨都不承認，真是可悲。
以前，我一直以爲民主是個好東西，但是被玩成這樣，還真是讓人傷感。

最後，github是一個技術論壇，請以後不要討論政治問題，請向會議官方申訴。

**Comment by corytu** [comment]
> First of all, the People's Republic of China(PRC) government has not recognized the San Francisco Peace Treaty since it signed. It is completely unreasonable for Taiwan independence to take something that the People's Republic of China(PRC) does not recognize at all.

No matter the PRC recognizes Treaty of San Francisco or not, the fact that it's signed and its contents are effective does not change. I am talking about facts, while your are talking about recognition. What does PRC's recognition have to do with the facts? I am confused by your points.

> Secondly, the 1992 Consensus only recognizes the People's Republic of China(PRC). The People's Republic of China has never acknowledged the two definitions that you have said. It is entirely the fabrication of Taiwan independence.

My said version of so-called "1992 Consensus" is the best one you can find in Taiwan from political parties that lean to PRC. In fact, people who go for Taiwan independence do not recognize the "1992 Consensus" at all. To me personally, "1992 Consensus" is simply a manipulating term, which is neither documented, nor do people on both sides really have consensus on what the "1992 Consensus" is.

> In the end, Taiwan has never been recognized internationally as an independent country and region, but is part of the People's Republic of China. Fabricating Taiwan as an independent region is entirely a Taiwan independence act of self-indulgence.
> 
> Why do you dare not reply to Taiwan authorities have not been recognized by the international community. What you said is not recognized by the People's Republic of China.

I need not because the recognition has nothing to do with what is factual or legally correct. Just because Taiwan authorities are not recognized by some international communities does not mean that they are a part of PRC.

Why do you not reply to "the PRC government has never had sovereignty over Taiwan, neither de facto nor de jure" part then? Share some facts which support the argument that Taiwan should be a part of PRC.

----

> Taiwan is a part of China.
> Please those who support Taiwan independence reflect on their own seriously where they come from in history.

Yeah like the USA is a part of the UK.

----

> 臺灣的先民要是知道後代成了這個樣子，不知做會做何感想。
> 如果留下一點爭辯的時間，稍微去學習一點臺灣歷史就能大概瞭解臺灣究竟和大陸之間的關係。只不過因爲日據時代，連國民黨都不承認，真是可悲。
> 以前，我一直以爲民主是個好東西，但是被玩成這樣，還真是讓人傷感。

臺灣的先民？您指的是南島語系民族嗎？那才真是臺灣先民啊，第一批呢。

稍微去學習一點歷史就能瞭解臺灣與中華人民共和國完全無關，臺灣為中華人民共和國之一部份的論點，不知由何而來。

> 最後，github是一個技術論壇，請以後不要討論政治問題，請向會議官方申訴。

GitHub是個技術論壇我同意，但若不要討論政治問題，也許先不要在GitHub上做出跟政治有關的commit 3ccc43c803602cb41cdb6578a61ee29b92b2fd4e？

**Comment by iofu728** [comment]
> 稍微去學習一點歷史就能瞭解臺灣與中華人民共和國完全無關

Yellow skin, speak Chinese, follow Confucianism and you think you're the man who has no relation with Mainland? 

非其鬼而祭之；諂也。見義不為,無勇也。

**Comment by Yannnnnnnnnnnn** [comment]
@corytu 
我想我們是同齡人，能不能換個地方battle，互通有無。至於你說的commit 3ccc43c，這個不過是遵從國際慣例，你跟我們爭論也解決不了問題，去跟國際社會爭論（比如讓美國在臺灣開設大使館，而不是辦事處）。

**Comment by MrOrz** [comment]
既然 @Yannnnnnnnnnnn 提到 github 是技術論壇，要不要試試技術解決?

https://github.com/JackieTseng/conference_call_for_paper/issues/16

**Comment by nobodxbodon** [comment]
@MrOrz how about forking this repo and making changes there?

**Comment by MrOrz** [comment]
@nobodxbodon 
> @MrOrz how about forking this repo and making changes there?

Well this is doable:
https://mrorz.github.io/conference_call_for_paper/conferences.html

It's just that I feel a bit guilty promoting the forked pages, since it's the original author's effort for putting all these information together. The website itself is not distributed under any licenses granting the others to reuse either.
